version: '3.3'

volumes:
  postgres-data:

services:
  postgres-db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: FL@m1n6o5
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/opt/postgres/data
      - /opt/postgres:/temp
      - /opt/postgres/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    networks:
      - post-net

networks:
  post-net:
