version: '3.3'

volumes:
  postgres-data:

services:
  test-db:
    container_name: postgres-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/opt/postgres/data
      - /opt/postgres:/opt/postrgres
      - /opt/postgres/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    networks:
      - postgres-net
networks:
  postgres-net:
