version: '3.3'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=mysql_db
      - MYSQL_ROOT_PASSWORD=FL@m1n6o5
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - mysql-net
volumes:
  db:
    driver: local
networks:
  mysql-net:
