version: "3.1"

services:
  mysql-liquibase:
    container_name: mysql-liquibase
    image: liquibase/liquibase
    environment:
      INSTALL_MYSQL: 1
    command: --url=jdbc:mysql://mysql_db:3306/SHELL?user=root&password=FL@m1n6o5 --changeLogFile=changelog.xml update
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts
    networks:
      - mysql-net
networks:
  mysql-net:
