version: '3.3'
volumes:
  data:
services:
  db:
    image: mariadb
    container_name: maria_db
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: mariadb
    volumes:
      - data:/var/lib/mysql
      - /opt/mariadb:/temp
    ports:
      - "3306:3306"
    networks:
      - mariadb-net
networks:
   mariadb-net:
