version: "3.1"

services:
  mssql-liquibase:
    container_name: mssql-liquibase
    image: liquibase/liquibase
    command: --url=jdbc:sqlserver://mssql-db:1433;encrypt=true;username=sa;password=mssqlSA; --changeLogFile=changelog.xml update
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts
    networks:
      - mssql-net
networks:
  mssql-net:
